[project]
name = "vla-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "lerobot[pi] @ git+https://github.com/huggingface/lerobot.git",
]
